language: node_js
node_js:
- 4.2.1
- 4.4.3
- 5.10.1
sudo: false
notifications:
  hipchat:
    rooms:
      secure: "TThMNOlBpt0egBpRSnZSV1MOIHEGb70aLAhPcHvX1cP61xA5yOppii8RU/OR/pHwR4YdGIgtRphrYCvSVtGjCpKTwuMI5WwOLeZeuX6zHgBs07gabsut/MgEjQcpd/xxkPHSY06gCS0fqDSLHINNFxXhziX0Aj93KLRa0pEM1CATLvnzTVGHRNsd4/U3ofH8pzWURRH7PJNcfqpn6Squ1oGwvwrlCpGMhDkhC3bSOFn6QFFq4bIg6Zpbm7XiW0UuK1aOaUVoHeSip2yQKPfnXYhti6mSIifFC/1J4llrf6rmuWnkO2k1lpqvEIFlAxZM2L80q37BiE9ctbx1fIPzfrq9Y0bkTBbgyW5RACacbOxHGwJhh3PgIXoM2Bxfb3a5PLH5dtIDQod6zbM0XolNY5xa3IccywE3Avwh4sqxqC2wei2S97s9PNlEHBJXLbp6lWG3KwmA687a0Xd3tQSBYKj97l83gRKaTyWougm6vrl2DY3JdKQK53J/eJciGYl50zf9Or1NcFUJ0LH6RMZW3Zy5516O85bpywLleli8p3uTU+vcOTr5Try2YsTfoFJsQalJ/RNRCzdHwuMQ6Fps6qLlJnEb7le28bSrVGE0/SL3at5uptGmJHDUVZsXyI2MgDTXAsoN7Qd2hNwPewUgvTJEWCo5sVD8/UMtOvXOuTY="
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
deploy:
  - provider: npm
    email: sysadmin@coreybutler.com
    api_key:
      secure: MOgI7+lBSuKtPzcQf1L2bNsb6kuhv7RvCbCbxorQEQ3grbHucrlRSTzmlDjvpOhXSILxLencoA06nkpZWuGJxS683dwslWzyn9NkudYq/Z1QRPQT8BtEWYSFF3YDq/10CGitp1wnVnwelHm7HCOEtr+ow/rtzV5q8o66BjDqkLkN8D5G7309d678HdVfSFFgR/i2q1qEeh4RWRFuydMzWUJebIGHqrw8POS1a+Wbp38Z8EeXFG8I49hDu+wtj4Hdlz0O+4T+ff6uDp04FnD08GLksjTiT/OyJROSNdcu0XcGaMxgmsSpT9IitnxvBzxHwkxls9SrzBL756vT4DPhrdg9FONjkSBUl3QqiwgV01LMFyI/j7ja9J/jxYFaRElQSYPMoRyYwTYEKNu6UtPdbx2mnCOnXoxgll8brDfTJOEjByokpr/rgN7ePpLA6gVMbDKPNtRzgRbOYAqi5rTFNEaS+4LmyZD8NSpykBsWkV/jgEZMjejmIrozTi6mEx2l+xt0c8cvLynDSXU3BIA2ne0UCInRommtbhSYwDleIkKLseyQhF2iJJHhiVbHkhd49qE103so57myMxMTYFE1gjhghUKtrC5eRGrSMLk+X4eaa4ypf4P7HCYLYmothb/hvS4xlof3T/PsD8fHjtjeRgBiikZ+LqzQtjipev5UPUc=
    on:
      tags: true
      repo: ngnjs/ngnx-http
  - provider: releases
    api_key:
      secure: ZcWoKlPJI3vhYxNchE5gdpZBfwRo9khsfwbHK1Mz//dO+lnWDKY5UjVutOSQM86VDM3BGiy7kkWC7Em08GRKuTbLIFGBWTEJi2DdnR97rmYaGbBOjmgZdmI4gQL+yB3pusPOfOn6rY8kocpfxPlTQSAj724Ypo3qemZTCHSEKH4=
    file:
      - "index.js"
      - "package.json"
      - "LICENSE"
    skip_cleanup: true
    on:
      tags: true
      repo: ngnjs/ngnx-http
