language: node_js
node_js:
- 5.10.1
sudo: false
notifications:
  hipchat:
    rooms:
      secure: "TThMNOlBpt0egBpRSnZSV1MOIHEGb70aLAhPcHvX1cP61xA5yOppii8RU/OR/pHwR4YdGIgtRphrYCvSVtGjCpKTwuMI5WwOLeZeuX6zHgBs07gabsut/MgEjQcpd/xxkPHSY06gCS0fqDSLHINNFxXhziX0Aj93KLRa0pEM1CATLvnzTVGHRNsd4/U3ofH8pzWURRH7PJNcfqpn6Squ1oGwvwrlCpGMhDkhC3bSOFn6QFFq4bIg6Zpbm7XiW0UuK1aOaUVoHeSip2yQKPfnXYhti6mSIifFC/1J4llrf6rmuWnkO2k1lpqvEIFlAxZM2L80q37BiE9ctbx1fIPzfrq9Y0bkTBbgyW5RACacbOxHGwJhh3PgIXoM2Bxfb3a5PLH5dtIDQod6zbM0XolNY5xa3IccywE3Avwh4sqxqC2wei2S97s9PNlEHBJXLbp6lWG3KwmA687a0Xd3tQSBYKj97l83gRKaTyWougm6vrl2DY3JdKQK53J/eJciGYl50zf9Or1NcFUJ0LH6RMZW3Zy5516O85bpywLleli8p3uTU+vcOTr5Try2YsTfoFJsQalJ/RNRCzdHwuMQ6Fps6qLlJnEb7le28bSrVGE0/SL3at5uptGmJHDUVZsXyI2MgDTXAsoN7Qd2hNwPewUgvTJEWCo5sVD8/UMtOvXOuTY="
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
deploy:
  - provider: npm
    email: sysadmin@coreybutler.com
    api_key:
      secure: "mef7iU8BHY3ddHwHIRnxLKKF35v7qbV1V4mx9RM0goLd5/seZAwRsfMrgVFMua8IcvBXxm2JzAfbjyUFOvYBHwzxATt89VoBvmINkpkAR07QDRUoV6OotPDm1/9nu8ZhDajXo2F3qVrYzYYVDS4c7hbv0DNeN5GbBmFF5gzZjgiS5H6v+XN2cr23pN3uQQTWtfCRc1q20fX6ZKJIz8YviGosmHoJwnvMhRsl/byuZxpDxrAHu+2wJJS0hdj/K4WT7Cps/PrrEDuyTYVNBcE6xKSuK9FQLz3ApDfQBtA7tzXFH/sjEMqL1EZF0BY2kPv7+HfDftnVQRx5h3b1n13lfCgaW5XUb3kpgQr14ufNiYngs88hXvDUrt0JTrATri9zGa5vfBC31ReYiSZ756HMrSK8NPRCsC7p5E8X7a2jGlAmpK/+HNyOpQ6H4xe1CjX2uq3V2eR/Co0qYPxNML/K5f42AsVI6oAoYdX2ltn4SBGvhjznPoAZsMDuE7dkNqIRJ/tloG17Ey/5krYbSDoh2sdpBw57FFRvEZK9vg+beX8QaJ370/96cr0dWMuXvDTahc8zpYm3gr/8wZzxOyK5WsHtjpnnBQtVHjyGzgr0TYobgZKWBGQv7aO3ud6GK7tCYF2NfUVwpItIVkpdFzZijx10+R0Pm+ASatW/ajWKx9A="
    on:
      tags: true
      repo: ngnjs/ngnx-http
  - provider: releases
    api_key:
      secure: ZcWoKlPJI3vhYxNchE5gdpZBfwRo9khsfwbHK1Mz//dO+lnWDKY5UjVutOSQM86VDM3BGiy7kkWC7Em08GRKuTbLIFGBWTEJi2DdnR97rmYaGbBOjmgZdmI4gQL+yB3pusPOfOn6rY8kocpfxPlTQSAj724Ypo3qemZTCHSEKH4=
    file:
      - "index.js"
      - "package.json"
      - "LICENSE"
    skip_cleanup: true
    on:
      tags: true
      repo: ngnjs/ngnx-http
